all:
	gcc -o ../../build/Quest_3 -Wall -Werror -Wextra main_executable_module.c data_sort.c ../data_libs/data_io.c ../data_libs/data_stat.c ../data_module/data_process.c ../yet_another_decision_module/decision.c

clean:
	rm -rf *.o hell

rebuild:
	all clean